spring.application.name=UserService

#database setup
spring.datasource.url=jdbc:mysql://localhost:3306/UserService?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update